# Generated by Django 5.2 on 2025-04-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_Master',
            fields=[
                ('Bill_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('S_No', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Years', models.IntegerField()),
                ('Monsths', models.IntegerField()),
                ('Days', models.IntegerField()),
                ('Gender', models.CharField(max_length=15)),
                ('Phone', models.BigIntegerField()),
                ('Alt_Phone', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Refered_By', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Particulars', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Discount', models.FloatField()),
                ('Amount', models.FloatField()),
                ('Date', models.DateField(auto_now=True)),
            ],
        ),
    ]
