# Generated by Django 5.2 on 2025-04-24 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_master',
            old_name='Monsths',
            new_name='Months',
        ),
    ]
