# Generated by Django 5.2 on 2025-04-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0002_rename_monsths_billing_master_months'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test_Master',
            fields=[
                ('S_No', models.IntegerField()),
                ('Test_Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Test_Name', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
            ],
        ),
    ]
