# Generated by Django 5.2 on 2025-04-24 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0003_test_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_master',
            name='Price',
        ),
        migrations.CreateModel(
            name='Billing_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_No', models.IntegerField()),
                ('Title', models.CharField(max_length=50)),
                ('Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('DOB', models.DateField()),
                ('Years', models.IntegerField()),
                ('Months', models.IntegerField()),
                ('Days', models.IntegerField()),
                ('Gender', models.CharField(max_length=15)),
                ('Phone', models.BigIntegerField()),
                ('Alt_Phone', models.BigIntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Refered_By', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('Particulars', models.CharField(max_length=50)),
                ('Price', models.FloatField()),
                ('Discount', models.FloatField()),
                ('Amount', models.FloatField()),
                ('Date', models.DateField(auto_now=True)),
                ('Bill_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitalApp.billing_master')),
            ],
        ),
    ]
