# Generated by Django 5.2 on 2025-04-25 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0004_remove_billing_master_price_billing_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_details',
            name='Address',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Alt_Phone',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Amount',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='DOB',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Days',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Discount',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Last_Name',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Months',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Phone',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Refered_By',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='S_No',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Title',
        ),
        migrations.RemoveField(
            model_name='billing_details',
            name='Years',
        ),
        migrations.RemoveField(
            model_name='billing_master',
            name='Particulars',
        ),
    ]
