# Generated by Django 5.2 on 2025-04-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0005_remove_billing_details_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_master',
            name='Advance',
            field=models.FloatField(default=0),
        ),
    ]
