# Generated by Django 5.2 on 2025-04-26 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0006_billing_master_advance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_master',
            old_name='Advance',
            new_name='Final_Amount',
        ),
    ]
