# Generated by Django 5.2 on 2025-04-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0007_rename_advance_billing_master_final_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_master',
            name='DOB',
        ),
        migrations.AlterField(
            model_name='billing_master',
            name='Days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='billing_master',
            name='Months',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='billing_master',
            name='Years',
            field=models.IntegerField(null=True),
        ),
    ]
