# Generated by Django 5.2 on 2025-04-27 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0008_remove_billing_master_dob_alter_billing_master_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_master',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
