# Generated by Django 5.2 on 2025-04-27 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0009_alter_billing_master_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
