# Generated by Django 5.2 on 2025-04-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0010_alter_billing_details_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='Date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='billing_master',
            name='Date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
