# Generated by Django 5.2 on 2025-04-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalApp', '0011_alter_billing_details_date_alter_billing_master_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_master',
            name='Advance',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
